version: '3.9'
services:
  db:
    image: 'postgres:15.4-alpine3.18'
    ports:
      - 5556:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: utility
    volumes:
      - pgdata-poc:/var/lib/postgresql/data

  web:
    image: manimr446/node-docker:v1.0
    command: npm run dev
    ports:
      - 5000:5000
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: utility
    depends_on:
      - db

volumes:
  pgdata-poc:
