version: '3.9'
services:
  web:
    build: .
    image: node-docker:v1
    command: sh -c 'npm run build && npm start'
    ports:
      - 5000:5000
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 5000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
