FROM node:18-alpine3.18

WORKDIR /usr/src/app

COPY package*.json .

ARG SERVER_HOST
ARG SERVER_PORT
ARG DB_HOST
ARG DB_PORT
ARG DB_DATABASE
ARG DB_USERNAME
ARG DB_PASSWORD

ENV SERVER_HOST=${SERVER_HOST}
ENV SERVER_PORT=${SERVER_PORT}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_DATABASE=${DB_DATABASE}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}

RUN npm ci

COPY . .

EXPOSE 5000

RUN npm run build

CMD [ "npm", "start" ]